name: myapp
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter

  text_form_field_wrapper: ^1.0.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  badges: ^3.1.2
 
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/categories/
    - assets/dishes/
    - assets/others/
    - assets/restaurants/
